export type EnterpriseCaseKind = 'scene' | 'case'

export interface EnterpriseCaseCatalogItem {
  number: number
  kind: EnterpriseCaseKind
  industry: string
  function: string
  title: string
  summary: string
  sourceStatus: string
  access: 'locked'
}

export const enterpriseIndustries = ["金融","制造","医疗健康","教育培训","零售电商","物流供应链","房地产建筑","能源环保","汽车交通","政务公共","媒体文娱","通信电子","农业食品","专业服务","游戏","互联网软件"] as const
export const enterpriseFunctions = ["市场营销","财务合规","销售客户","运营客服","人事行政","数据分析","项目管理","产品设计","高管战略"] as const

export const enterpriseCaseCatalog: readonly EnterpriseCaseCatalogItem[] = [
  { number: 1, kind: 'scene', industry: '金融', function: '市场营销', title: "金融知识科普内容矩阵", summary: "金融产品说明书晦涩难懂，传统营销内容转化率低。", sourceStatus: "参考场景", access: 'locked' },
  { number: 2, kind: 'scene', industry: '金融', function: '财务合规', title: "合规审查报告三Agent协作", summary: "金融合规审查报告撰写耗时长、易遗漏。", sourceStatus: "📎 已验证", access: 'locked' },
  { number: 3, kind: 'scene', industry: '金融', function: '财务合规', title: "监管报送自动化", summary: "银行每月需向监管报送十余类报告，合规岗三人轮班仍常加班。", sourceStatus: "📎 已验证", access: 'locked' },
  { number: 4, kind: 'scene', industry: '金融', function: '销售客户', title: "理财产品智能推荐方案", summary: "理财经理面对数百款产品难以快速匹配客户需求。", sourceStatus: "参考场景", access: 'locked' },
  { number: 5, kind: 'scene', industry: '金融', function: '销售客户', title: "保险计划书分钟级生成", summary: "传统保险计划书需代理人手工填写产品参数、测算保费、排版格式，一份耗时1-2小时。", sourceStatus: "参考场景", access: 'locked' },
  { number: 6, kind: 'scene', industry: '金融', function: '运营客服', title: "银行智能客服知识库", summary: "银行客服重复性问题占80%以上，新人培训周期长。", sourceStatus: "参考场景", access: 'locked' },
  { number: 7, kind: 'scene', industry: '金融', function: '人事行政', title: "金融从业者合规培训材料", summary: "金融合规政策频繁更新，培训材料制作耗时且易过时。", sourceStatus: "参考场景", access: 'locked' },
  { number: 8, kind: 'scene', industry: '金融', function: '数据分析', title: "信贷风险评估报告", summary: "信贷审批员面对企业财报和经营数据需人工计算数十项财务指标，单份耗时1-2小时且易出错。", sourceStatus: "参考场景", access: 'locked' },
  { number: 9, kind: 'scene', industry: '金融', function: '项目管理', title: "投行尽调文档结构化", summary: "投行尽调过程产生海量文档、访谈记录、数据表格，整理耗时且信息碎片化严重。", sourceStatus: "参考场景", access: 'locked' },
  { number: 10, kind: 'scene', industry: '制造', function: '项目管理', title: "工单智能流转与跟踪", summary: "离散制造车间异常处理流程长：巡检发现异常→口头通知班组长→手写工单→人工派单→纸质跟踪，平均耗时长。", sourceStatus: "📎 已验证", access: 'locked' },
  { number: 11, kind: 'scene', industry: '制造', function: '数据分析', title: "生产数据看板自动生成", summary: "制造企业MES/ERP数据分散在多个系统，管理层需每天手工汇总才能了解全局。", sourceStatus: "参考场景", access: 'locked' },
  { number: 12, kind: 'scene', industry: '制造', function: '销售客户', title: "设备报价方案一键生成", summary: "非标设备报价需反复对照BOM表、工艺参数、原材料价格，人工计算易出错且响应慢。", sourceStatus: "参考场景", access: 'locked' },
  { number: 13, kind: 'scene', industry: '制造', function: '人事行政', title: "产线智能排班", summary: "产线排班需综合考虑订单量、人员技能、工时法规、设备产能四维因素，人工排班耗时长且难以最优。", sourceStatus: "参考场景", access: 'locked' },
  { number: 14, kind: 'scene', industry: '制造', function: '运营客服', title: "设备售后知识库", summary: "设备维修手册厚达数百页，售后工程师现场查找费时且新人难上手。", sourceStatus: "参考场景", access: 'locked' },
  { number: 15, kind: 'scene', industry: '制造', function: '财务合规', title: "BOM物料成本自动核算", summary: "非标装备制造企业多层级BOM清单动辄数百条子物料，成本会计手工拆解、叠加损耗和加工费，稍有不慎就出错，月末加班是常态。", sourceStatus: "📎 已验证", access: 'locked' },
  { number: 16, kind: 'scene', industry: '制造', function: '市场营销', title: "产品选型指南智能生成", summary: "工业品参数复杂，客户自助选型困难，销售人员需反复解答同类问题。", sourceStatus: "参考场景", access: 'locked' },
  { number: 17, kind: 'scene', industry: '制造', function: '项目管理', title: "设备维护计划自动排程", summary: "工厂设备维护依赖人工记忆和经验排期，漏保、过保频发。", sourceStatus: "参考场景", access: 'locked' },
  { number: 18, kind: 'scene', industry: '医疗健康', function: '运营客服', title: "患者智能问答系统", summary: "门诊咨询台每天面对大量重复问题（挂号流程/科室位置/检查须知），人力成本高且回答一致性差。", sourceStatus: "参考场景", access: 'locked' },
  { number: 19, kind: 'scene', industry: '医疗健康', function: '数据分析', title: "患者数据统计分析报告", summary: "医院运营管理需要按科室/病种/时段的多维数据分析，传统手工汇总耗时长。", sourceStatus: "参考场景", access: 'locked' },
  { number: 20, kind: 'scene', industry: '医疗健康', function: '市场营销', title: "健康科普多平台内容矩阵", summary: "医疗机构想做科普但专业内容难做\"说人话\"的转化。", sourceStatus: "参考场景", access: 'locked' },
  { number: 21, kind: 'scene', industry: '医疗健康', function: '人事行政', title: "医护智能排班", summary: "医院排班需平衡科室需求、人员资质、夜班公平性、连续工时法规等多重约束，护士长排一次班要半天。", sourceStatus: "参考场景", access: 'locked' },
  { number: 22, kind: 'scene', industry: '医疗健康', function: '财务合规', title: "医保结算单自动核对", summary: "医保结算涉及海量明细条目，人工逐条核对费时且易出错漏。", sourceStatus: "参考场景", access: 'locked' },
  { number: 23, kind: 'scene', industry: '医疗健康', function: '项目管理', title: "临床试验数据整理", summary: "临床试验产生大量CRF表格和检测数据，数据管理员手工录入和清洗耗时数周。", sourceStatus: "参考场景", access: 'locked' },
  { number: 24, kind: 'scene', industry: '教育培训', function: '市场营销', title: "多平台招生内容批量生产", summary: "教培机构每天需要在公众号/知乎/头条号/小红书等多平台发布招生内容，人工撰写耗时长、质量不稳定。", sourceStatus: "📎 已验证", access: 'locked' },
  { number: 25, kind: 'scene', industry: '教育培训', function: '运营客服', title: "报名-审核-缴费智能引导", summary: "教培机构招生流程（咨询→报名→审核→缴费→开课）环节多、易脱节，体验差导致流失率高。", sourceStatus: "📎 已验证", access: 'locked' },
  { number: 26, kind: 'scene', industry: '教育培训', function: '产品设计', title: "在线课程大纲智能生成", summary: "课程开发人员设计新课大纲需查阅大量资料，从选题到知识点拆解耗时数天。", sourceStatus: "参考场景", access: 'locked' },
  { number: 27, kind: 'scene', industry: '教育培训', function: '数据分析', title: "学员学习行为分析", summary: "在线教育平台学员数据多但缺乏分析能力，流失预警靠经验判断。", sourceStatus: "参考场景", access: 'locked' },
  { number: 28, kind: 'scene', industry: '教育培训', function: '人事行政', title: "教师绩效考核数据汇总", summary: "培训机构教师考核需汇总教学质量评估/学员评价/课时统计/续费率等多维数据，HR每月手动整理耗时2-3天。", sourceStatus: "参考场景", access: 'locked' },
  { number: 29, kind: 'scene', industry: '教育培训', function: '市场营销', title: "留学案例库智能营销", summary: "留学顾问面对不同背景的客户，需要快速匹配相似成功案例来建立信任。", sourceStatus: "参考场景", access: 'locked' },
  { number: 30, kind: 'scene', industry: '零售电商', function: '市场营销', title: "内容工厂：四Agent并行产素材", summary: "电商团队每天需要产出大量营销素材（商品详情/社媒推文/广告文案/活动海报），单靠人工效率瓶颈明显。", sourceStatus: "📎 已验证", access: 'locked' },
  { number: 31, kind: 'scene', industry: '零售电商', function: '运营客服', title: "智能客服承接高频问答", summary: "电商客服重复性问题（物流查询/退换货/尺码建议）占70%以上，大促期间人力缺口大。", sourceStatus: "📎 已验证", access: 'locked' },
  { number: 32, kind: 'scene', industry: '零售电商', function: '数据分析', title: "销售数据自动分析报告", summary: "运营人员每月需手动汇总各渠道销售数据做分析报告，拉数据+做图表+写结论耗去一整天。", sourceStatus: "参考场景", access: 'locked' },
  { number: 33, kind: 'scene', industry: '零售电商', function: '市场营销', title: "私域客户智能分层运营", summary: "客户分层依赖人工打标签，滞后且不准确，千人一面的推送导致转化率低。", sourceStatus: "📎 已验证", access: 'locked' },
  { number: 34, kind: 'scene', industry: '零售电商', function: '人事行政', title: "AI面试与门店运营决策", summary: "连锁零售门店面临招聘量大、面试效率低、门店运营决策靠经验的痛点。", sourceStatus: "📎 官方标杆", access: 'locked' },
  { number: 35, kind: 'scene', industry: '零售电商', function: '运营客服', title: "社群运营智能日报", summary: "社群运营人员同时管理数十个微信群，每天需花半小时翻聊天记录才能了解社群状况。", sourceStatus: "参考场景", access: 'locked' },
  { number: 36, kind: 'scene', industry: '零售电商', function: '市场营销', title: "商品描述批量优化", summary: "跨境电商上新时需为数百个SKU撰写多语言商品标题和描述，人工逐一撰写效率极低。", sourceStatus: "参考场景", access: 'locked' },
  { number: 37, kind: 'scene', industry: '零售电商', function: '市场营销', title: "直播带货脚本智能生成", summary: "直播带货需要专业脚本（产品介绍/互动话术/逼单节奏/应急处理），中小商家缺乏专业策划能力。", sourceStatus: "参考场景", access: 'locked' },
  { number: 38, kind: 'scene', industry: '零售电商', function: '数据分析', title: "大促复盘报告自动生成", summary: "每次大促后运营需花2-3天从各平台导出数据做复盘报告。", sourceStatus: "参考场景", access: 'locked' },
  { number: 39, kind: 'scene', industry: '零售电商', function: '人事行政', title: "门店员工分岗培训", summary: "连锁门店新员工培训需覆盖收银/理货/客服/安全等多岗位技能，传统集中培训周期长、效果难追踪。", sourceStatus: "参考场景", access: 'locked' },
  { number: 40, kind: 'scene', industry: '物流供应链', function: '数据分析', title: "供应链智能分析与亏损排查", summary: "物流企业供应链数据庞大，亏损分析需手动跨系统调数据\"熬几天\"。", sourceStatus: "📎 官方标杆", access: 'locked' },
  { number: 41, kind: 'scene', industry: '物流供应链', function: '项目管理', title: "报关文件自动准备", summary: "跨境物流报关需准备十几种文件，人工核对HS编码、计算关税易出错。", sourceStatus: "参考场景", access: 'locked' },
  { number: 42, kind: 'scene', industry: '物流供应链', function: '运营客服', title: "物流轨迹异常自动预警", summary: "物流异常（延迟/丢件/退回）传统靠人工盯监控或客户投诉后才发现，反应滞后。", sourceStatus: "参考场景", access: 'locked' },
  { number: 43, kind: 'scene', industry: '物流供应链', function: '数据分析', title: "运输成本优化分析", summary: "物流企业运输成本受路线/油价/车型/货量等多因素影响，传统靠调度经验难以全局优化。", sourceStatus: "参考场景", access: 'locked' },
  { number: 44, kind: 'scene', industry: '物流供应链', function: '项目管理', title: "异常订单自动处理流", summary: "物流企业日均产生数百条异常订单（地址不详/拒收/退回/破损），传统需人工逐条判断处理方式。", sourceStatus: "参考场景", access: 'locked' },
  { number: 45, kind: 'scene', industry: '物流供应链', function: '数据分析', title: "冷链温控数据监控", summary: "冷链物流对温度控制要求严格，传统人工抄表或每天巡检查看温度记录，存在监控盲区。", sourceStatus: "参考场景", access: 'locked' },
  { number: 46, kind: 'scene', industry: '房地产建筑', function: '人事行政', title: "多部门AI数字员工部署", summary: "大型房企行政/财务/营销等部门存在大量重复性事务（数据录入/报表汇总/通知发送/资料归档），消耗大量人力。", sourceStatus: "📎 官方标杆", access: 'locked' },
  { number: 47, kind: 'scene', industry: '房地产建筑', function: '市场营销', title: "楼盘推广文案批量生成", summary: "房产经纪人每天需在朋友圈/安居客/贝壳等多平台发布房源信息，手动撰写适配各平台风格的文案效率低。", sourceStatus: "参考场景", access: 'locked' },
  { number: 48, kind: 'scene', industry: '房地产建筑', function: '项目管理', title: "工程进度报告自动生成", summary: "建筑工地每天需提交施工日志和进度报告，施工员手写后还需文员汇总排版，耗时且格式不统一。", sourceStatus: "参考场景", access: 'locked' },
  { number: 49, kind: 'scene', industry: '房地产建筑', function: '数据分析', title: "设备巡检数据管理", summary: "物业公司管理多个小区的消防/电梯/配电设备，巡检数据分散在纸质表格和照片中，难以汇总分析。", sourceStatus: "参考场景", access: 'locked' },
  { number: 50, kind: 'scene', industry: '房地产建筑', function: '销售客户', title: "客户匹配智能推荐", summary: "房产经纪人面对数百套房源，人工为客户匹配效率低且主观性强。", sourceStatus: "参考场景", access: 'locked' },
  { number: 51, kind: 'scene', industry: '能源环保', function: '数据分析', title: "能源消耗监测与报告", summary: "工厂/园区能耗数据分散在电表/水表/气表中，人工抄表汇总耗时且无可视化分析。", sourceStatus: "参考场景", access: 'locked' },
  { number: 52, kind: 'scene', industry: '能源环保', function: '项目管理', title: "碳资产管理台账", summary: "碳交易市场要求企业精确核算碳排放量并按规报告，传统人工核算费时且易出错。", sourceStatus: "参考场景", access: 'locked' },
  { number: 53, kind: 'scene', industry: '能源环保', function: '财务合规', title: "环境合规报告自动生成", summary: "企业需按季度向环保部门提交排污许可证执行报告和环境监测数据，人工从多个系统汇总数据繁琐易错。", sourceStatus: "参考场景", access: 'locked' },
  { number: 54, kind: 'scene', industry: '能源环保', function: '人事行政', title: "安全培训材料自动更新", summary: "电力/化工等高风险行业安全培训材料需随法规更新频繁修订，HR跟进吃力。", sourceStatus: "参考场景", access: 'locked' },
  { number: 55, kind: 'scene', industry: '汽车交通', function: '市场营销', title: "车型对比内容自动生成", summary: "汽车垂直媒体和经销商需要大量车型对比内容，人工从参数表到成文需2-3小时一篇。", sourceStatus: "参考场景", access: 'locked' },
  { number: 56, kind: 'scene', industry: '汽车交通', function: '运营客服', title: "车主服务知识库", summary: "车企/4S店客服面对大量重复问题（保养周期/故障灯含义/保险理赔流程），新人需培训2-4周才能独立上岗。", sourceStatus: "参考场景", access: 'locked' },
  { number: 57, kind: 'scene', industry: '汽车交通', function: '数据分析', title: "4S店售后运营分析", summary: "4S店集团需汇总各门店售后数据（进厂台次/客单价/配件消耗/工时效率）做经营分析，传统靠各店手工上报、总部汇总，周期长且数据不一致。", sourceStatus: "参考场景", access: 'locked' },
  { number: 58, kind: 'scene', industry: '政务公共', function: '运营客服', title: "政务知识问答智能体", summary: "政务大厅窗口每天面对大量重复性政策咨询（办事流程/材料清单/办理时限），人力成本高且回答标准不一。", sourceStatus: "📎 已验证", access: 'locked' },
  { number: 59, kind: 'scene', industry: '政务公共', function: '数据分析', title: "民生数据报告自动生成", summary: "政府部门定期需汇总多部门数据形成民生分析报告（就业/物价/收入/社保），传统人工跨部门协调数据周期长。", sourceStatus: "参考场景", access: 'locked' },
  { number: 60, kind: 'scene', industry: '政务公共', function: '人事行政', title: "政策解读材料自动生成", summary: "新政策发布后需快速产出面向公众的解读材料，传统人工撰写周期长影响政策传播时效。", sourceStatus: "参考场景", access: 'locked' },
  { number: 61, kind: 'scene', industry: '政务公共', function: '项目管理', title: "政府采购招投标文件准备", summary: "政府采购项目投标需准备大量资质文件和技术方案，每次都要从零整理，耗时且易遗漏。", sourceStatus: "参考场景", access: 'locked' },
  { number: 62, kind: 'scene', industry: '媒体文娱', function: '市场营销', title: "影视宣发素材批量生产", summary: "影视项目宣发期需在短时间内产出海报文案/短视频脚本/微博话题/公众号推文等大量不同形态内容。", sourceStatus: "参考场景", access: 'locked' },
  { number: 63, kind: 'scene', industry: '媒体文娱', function: '产品设计', title: "综艺节目策划方案生成", summary: "综艺节目策划需从零构思环节设计/嘉宾搭配/话题设置，创意枯竭是常态。", sourceStatus: "参考场景", access: 'locked' },
  { number: 64, kind: 'scene', industry: '媒体文娱', function: '数据分析', title: "收视流量数据周报", summary: "视频平台运营需每周汇总各频道播放量/互动量/用户画像数据做运营周报。", sourceStatus: "参考场景", access: 'locked' },
  { number: 65, kind: 'scene', industry: '媒体文娱', function: '市场营销', title: "创意提案批量生成", summary: "广告公司在比稿阶段需为同一客户产出多个创意方向，人工构思数量有限且耗时长。", sourceStatus: "参考场景", access: 'locked' },
  { number: 66, kind: 'scene', industry: '通信电子', function: '项目管理', title: "通信网络规划方案生成", summary: "通信网络规划需综合考虑覆盖区域/容量需求/地形/干扰/成本等多维参数，人工方案设计周期长。", sourceStatus: "参考场景", access: 'locked' },
  { number: 67, kind: 'scene', industry: '通信电子', function: '运营客服', title: "网络故障诊断知识库", summary: "通信网络故障类型复杂，一线运维工程师遇到罕见故障查找手册耗时长，影响修复时效。", sourceStatus: "参考场景", access: 'locked' },
  { number: 68, kind: 'scene', industry: '通信电子', function: '市场营销', title: "技术白皮书自动生成", summary: "芯片/通信设备企业需要定期产出面向客户的技术白皮书，工程师写文档耗时且风格不统一。", sourceStatus: "参考场景", access: 'locked' },
  { number: 69, kind: 'scene', industry: '通信电子', function: '数据分析', title: "客户投诉智能分析", summary: "运营商每天收到海量客户投诉，传统需人工逐条分类和定级，效率低且容易遗漏高优先级问题。", sourceStatus: "参考场景", access: 'locked' },
  { number: 70, kind: 'scene', industry: '农业食品', function: '市场营销', title: "农产品溯源故事自动生成", summary: "农产品电商需要\"有温度的内容\"打动消费者，但产地故事全靠人工编撰。", sourceStatus: "参考场景", access: 'locked' },
  { number: 71, kind: 'scene', industry: '农业食品', function: '数据分析', title: "农产品价格行情监控", summary: "农产品贸易商需要持续监控多个批发市场的价格变化来决策采购时机，人工收集数据滞后且不完整。", sourceStatus: "参考场景", access: 'locked' },
  { number: 72, kind: 'scene', industry: '农业食品', function: '数据分析', title: "养殖数据智能监控", summary: "规模化养殖场需要监控温湿度/饲料消耗/饮水量/生长速度等多维数据，传统靠人工记录难以实时预警。", sourceStatus: "参考场景", access: 'locked' },
  { number: 73, kind: 'scene', industry: '农业食品', function: '运营客服', title: "连锁餐饮门店SOP管理", summary: "连锁餐饮门店SOP文档（菜品配方/制作流程/食品安全规范）厚达数百页，新员工查阅效率低、执行容易走样。", sourceStatus: "参考场景", access: 'locked' },
  { number: 74, kind: 'scene', industry: '专业服务', function: '财务合规', title: "审计底稿自动化", summary: "会计师事务所审计忙季底稿编制工作量巨大，初级审计员大量时间花在机械性的抽样/计算/填表上。", sourceStatus: "📎 已验证", access: 'locked' },
  { number: 75, kind: 'scene', industry: '专业服务', function: '销售客户', title: "行业研报快速转化", summary: "咨询/券商机构需将动辄百页的行业研报转化为客户能快速阅读的摘要，人工提炼耗时。", sourceStatus: "参考场景", access: 'locked' },
  { number: 76, kind: 'scene', industry: '专业服务', function: '人事行政', title: "法律文书模板化管理", summary: "律所日常起草法律文书（起诉状/答辩状/律师函/法律意见书）存在大量重复性工作，每份虽案情不同但格式和基础条款相似。", sourceStatus: "参考场景", access: 'locked' },
  { number: 77, kind: 'scene', industry: '专业服务', function: '销售客户', title: "判例检索与分析摘要", summary: "律师接到新案件需快速检索相关判例和法规来评估案情，传统翻阅数据库效率低。", sourceStatus: "参考场景", access: 'locked' },
  { number: 78, kind: 'scene', industry: '专业服务', function: '人事行政', title: "候选人评估自动化", summary: "猎头/HR面对海量简历时人工筛选疲劳，容易漏掉潜在合适人选。", sourceStatus: "参考场景", access: 'locked' },
  { number: 79, kind: 'scene', industry: '游戏', function: '市场营销', title: "社区运营智能化", summary: "游戏社区运营需要持续产出互动内容和活动方案来维持玩家活跃度，创意枯竭和人力不足是主要痛点。", sourceStatus: "参考场景", access: 'locked' },
  { number: 80, kind: 'scene', industry: '游戏', function: '数据分析', title: "运营数据自动化", summary: "游戏运营每天需关注DAU/付费率/ARPU/留存率等数十项指标，人工从多个后台拉数据做日报耗时。", sourceStatus: "参考场景", access: 'locked' },
  { number: 81, kind: 'scene', industry: '游戏', function: '运营客服', title: "玩家投诉智能分类", summary: "大型手游每天收到数千条玩家投诉，人工逐条分类和定级效率极低，高风险问题（退款纠纷/账号被盗）可能被淹没。", sourceStatus: "参考场景", access: 'locked' },
  { number: 82, kind: 'scene', industry: '互联网软件', function: '市场营销', title: "GEO优化内容生成", summary: "AI搜索引擎（如Perplexity/豆包）正成为新的流量入口，但传统SEO内容无法被AI搜索收录。", sourceStatus: "📎 已验证", access: 'locked' },
  { number: 83, kind: 'scene', industry: '互联网软件', function: '市场营销', title: "多平台技术博客自动运营", summary: "技术公司需要持续产出技术博客来建设品牌和SEO，但工程师写文章耗时且风格不统一。", sourceStatus: "参考场景", access: 'locked' },
  { number: 84, kind: 'scene', industry: '互联网软件', function: '销售客户', title: "客户跟进简报自动生成", summary: "B2B销售同时跟进数十家客户，每次拜访前需要快速回顾客户历史。", sourceStatus: "📎 已验证", access: 'locked' },
  { number: 85, kind: 'scene', industry: '互联网软件', function: '运营客服', title: "流失客户智能挽回", summary: "SaaS企业客户流失是核心痛点，传统靠人工判断流失风险效率低且错过最佳挽回时机。", sourceStatus: "📎 已验证", access: 'locked' },
  { number: 86, kind: 'scene', industry: '互联网软件', function: '市场营销', title: "企业微信群健康度监控", summary: "企业微信运营人员同时管理数十个客户群，难以实时掌握每个群的健康状况。", sourceStatus: "📎 已验证", access: 'locked' },
  { number: 87, kind: 'scene', industry: '互联网软件', function: '运营客服', title: "全天候智能接待", summary: "中小企业没有能力配置7×24小时客服团队，非工作时间的客户咨询大量流失。", sourceStatus: "参考场景", access: 'locked' },
  { number: 88, kind: 'scene', industry: '互联网软件', function: '运营客服', title: "客服数据分析周报", summary: "客服主管需要周报来驱动服务质量改善，但人工分析客服数据耗时长。", sourceStatus: "参考场景", access: 'locked' },
  { number: 89, kind: 'scene', industry: '互联网软件', function: '市场营销', title: "产品Landing Page快速搭建", summary: "SaaS创业团队需要频繁制作产品落地页做A/B测试，但设计资源紧张。", sourceStatus: "参考场景", access: 'locked' },
  { number: 90, kind: 'scene', industry: '互联网软件', function: '人事行政', title: "新员工入职培训自动化", summary: "HR需为新员工逐一准备培训计划/资料包/考核安排，重复性高且容易遗漏。", sourceStatus: "参考场景", access: 'locked' },
  { number: 91, kind: 'scene', industry: '互联网软件', function: '财务合规', title: "合同条款智能审查", summary: "法务审核合同时需逐条比对条款清单和公司合规要求，一份标准合同审核耗时30-60分钟。", sourceStatus: "参考场景", access: 'locked' },
  { number: 92, kind: 'scene', industry: '互联网软件', function: '财务合规', title: "费用报销智能审核", summary: "财务每月审核数百张报销单，人工逐张核对发票真伪/金额/政策合规性，耗时且容易疲劳出错。", sourceStatus: "参考场景", access: 'locked' },
  { number: 93, kind: 'scene', industry: '互联网软件', function: '产品设计', title: "用户反馈智能分类与排序", summary: "产品团队每天从多个渠道（应用商店/客服工单/NPS调研/社区）收到大量用户反馈，人工分类分析效率极低。", sourceStatus: "参考场景", access: 'locked' },
  { number: 94, kind: 'scene', industry: '互联网软件', function: '产品设计', title: "PRD自动生成与评审", summary: "产品经理写PRD需要从需求调研到文档输出，流程长且格式不一。", sourceStatus: "参考场景", access: 'locked' },
  { number: 95, kind: 'scene', industry: '互联网软件', function: '高管战略', title: "竞品分析报告自动生成", summary: "管理层做竞品分析需要手动搜集多个竞品的信息并整理对比，耗时且容易遗漏。", sourceStatus: "参考场景", access: 'locked' },
  { number: 96, kind: 'scene', industry: '互联网软件', function: '项目管理', title: "周报自动生成", summary: "大多数职场人写周报是\"周五下午最痛苦的事\"——零散的工作记录难以系统化，写出来要么流水账要么空洞无物。", sourceStatus: "参考场景", access: 'locked' },
  { number: 97, kind: 'scene', industry: '互联网软件', function: '项目管理', title: "多文档整合提炼", summary: "工作中常需处理多份长文档（会议纪要/政策文件/项目资料），逐份通读再手工整合信息耗时2-3小时且容易遗漏。", sourceStatus: "参考场景", access: 'locked' },
  { number: 98, kind: 'scene', industry: '互联网软件', function: '数据分析', title: "Excel批量数据清洗", summary: "日常工作中的业务数据表格（500行左右）普遍存在空值/重复/格式混乱/分类不清的问题，人工清洗统计需要1-2小时且容易看错行、漏统计。", sourceStatus: "参考场景", access: 'locked' },
  { number: 99, kind: 'scene', industry: '互联网软件', function: '产品设计', title: "PPT自动生成", summary: "制作一份像样的PPT需要先搭框架、填内容、调格式、配图表，一套流程下来至少半天。", sourceStatus: "参考场景", access: 'locked' },
  { number: 100, kind: 'scene', industry: '互联网软件', function: '高管战略', title: "AI转型路径规划", summary: "企业想做AI转型但不知从哪里切入、如何分阶段落地。", sourceStatus: "参考场景", access: 'locked' },
  { number: 1, kind: 'case', industry: '金融', function: '财务合规', title: "平安银行：合规审查自动化", summary: "平安银行面临监管报送和合规审查的双重压力，传统人工审查效率难以满足日益增长的合规要求。", sourceStatus: "📎 官方标杆", access: 'locked' },
  { number: 2, kind: 'case', industry: '金融', function: '财务合规', title: "某区域性银行：合规报告周期缩短4-5成", summary: "该银行每月需向监管报送十余类合规报告，合规岗三人轮班仍常加班到深夜。", sourceStatus: "📎 已验证·企业旗舰版", access: 'locked' },
  { number: 3, kind: 'case', industry: '金融', function: '数据分析', title: "某保险公司：理赔数据智能分析", summary: "该保险公司月均处理数万件理赔，欺诈风险识别依赖人工经验判断，漏网率高。", sourceStatus: "参考场景", access: 'locked' },
  { number: 4, kind: 'case', industry: '金融', function: '市场营销', title: "某基金公司：投资者教育内容矩阵", summary: "该基金公司产品说明书专业晦涩，投资者理解门槛高、营销转化差。", sourceStatus: "参考场景", access: 'locked' },
  { number: 5, kind: 'case', industry: '金融', function: '运营客服', title: "某证券公司：投研报告辅助生成", summary: "该证券公司研究所分析师撰写研究报告时，数据搜集和初稿撰写占去60%以上时间。", sourceStatus: "参考场景", access: 'locked' },
  { number: 6, kind: 'case', industry: '金融', function: '销售客户', title: "某寿险公司：保险计划书分钟级生成", summary: "该寿险公司代理人数量庞大，每位代理人每天最多只能为2-3位客户手工制作保险计划书，效率成业务增长的瓶颈。", sourceStatus: "参考场景", access: 'locked' },
  { number: 7, kind: 'case', industry: '金融', function: '人事行政', title: "某保险公司：新员工合规培训自动化", summary: "该保险公司每年大量新入职的销售和客服人员需完成合规培训，HR每月手工更新培训材料和出卷，工作量大且滞后于政策更新。", sourceStatus: "参考场景", access: 'locked' },
  { number: 8, kind: 'case', industry: '金融', function: '项目管理', title: "某投行：项目尽调文档管理", summary: "该投行每次IPO/并购项目尽调产生上千份文档，项目组手动整理耗时巨大、信息碎片化严重。", sourceStatus: "参考场景", access: 'locked' },
  { number: 9, kind: 'case', industry: '金融', function: '数据分析', title: "某券商研究所：行业研报快速转化", summary: "该券商研究所产出大量百页以上的深度行业研报，但客户阅读完成率低。", sourceStatus: "参考场景", access: 'locked' },
  { number: 10, kind: 'case', industry: '制造', function: '项目管理', title: "某离散制造企业：质检与工单智能体", summary: "该离散制造企业质检科过去靠目检，每班仅覆盖约六成产线，异常常到客户端才暴露。", sourceStatus: "📎 已验证", access: 'locked' },
  { number: 11, kind: 'case', industry: '制造', function: '数据分析', title: "某汽车零部件厂：生产看板自动化", summary: "该零部件厂每天早会前车间主任需手工汇总各条产线的产量/良率/设备状态/OEE数据填入Excel，耗时1小时且数据滞后。", sourceStatus: "参考场景", access: 'locked' },
  { number: 12, kind: 'case', industry: '制造', function: '销售客户', title: "某化工设备企业：标书自动生成", summary: "该企业每次投标需销售+技术+财务三人协作——销售整理商务要求/技术匹配设备型号/财务核算成本和报价，准备一份标书平均耗时2天。", sourceStatus: "参考场景", access: 'locked' },
  { number: 13, kind: 'case', industry: '制造', function: '人事行政', title: "某电子厂：产线智能排班", summary: "该电子厂旺季订单波动大，HR每天需手工调整200+工人的排班，既要保交付又要控加班成本。", sourceStatus: "参考场景", access: 'locked' },
  { number: 14, kind: 'case', industry: '制造', function: '运营客服', title: "某家电企业：售后知识库", summary: "该企业售后工程师分布全国，遇到疑难故障需电话咨询总部技术支持，响应慢且沟通效率低。", sourceStatus: "参考场景", access: 'locked' },
  { number: 15, kind: 'case', industry: '制造', function: '财务合规', title: "山东某非标装备企业：BOM成本核算", summary: "该非标装备企业产品多为个性化定制，每台设备BOM清单动辄数百行，财务每月末手工核算单台成本需5天，常加班到凌晨。", sourceStatus: "📎 已验证", access: 'locked' },
  { number: 16, kind: 'case', industry: '制造', function: '市场营销', title: "某工业品企业：产品选型指南", summary: "该企业产品型号数百种、参数复杂，销售和客户选型常出错，导致后续退换货和客诉。", sourceStatus: "参考场景", access: 'locked' },
  { number: 17, kind: 'case', industry: '制造', function: '项目管理', title: "某工厂：设备维护计划自动化", summary: "该工厂有300+台设备，维护排程全靠一位老师傅的经验和记忆，漏保/过保时有发生。", sourceStatus: "参考场景", access: 'locked' },
  { number: 18, kind: 'case', industry: '医疗健康', function: '运营客服', title: "某三甲医院：患者服务知识库", summary: "该医院门诊咨询台每天面对数千次患者咨询（挂号流程/科室/检查须知/报告查询），4名导诊员应接不暇、患者排队等待长。", sourceStatus: "参考场景", access: 'locked' },
  { number: 19, kind: 'case', industry: '医疗健康', function: '数据分析', title: "某医药企业：临床试验数据整理", summary: "该CRO企业每个临床试验项目产生上千份CRF表格，数据管理员手工录入和清洗耗时4-6周。", sourceStatus: "参考场景", access: 'locked' },
  { number: 20, kind: 'case', industry: '医疗健康', function: '市场营销', title: "某互联网医疗平台：健康科普矩阵", summary: "该平台拥有数十位医生资源但内容产出量一直上不去——医生忙于诊疗没时间写科普。", sourceStatus: "参考场景", access: 'locked' },
  { number: 21, kind: 'case', industry: '医疗健康', function: '人事行政', title: "某连锁诊所：医护排班自动化", summary: "该连锁诊所旗下20家门店180名医护人员，排班需综合考虑各科室需求/人员资质/工时法规/公平性，HR主管每次排班耗费半天。", sourceStatus: "参考场景", access: 'locked' },
  { number: 22, kind: 'case', industry: '医疗健康', function: '项目管理', title: "某医疗器械公司：注册文档管理", summary: "该企业每年申报多款医疗器械注册证，每款产品需准备数百页技术文档和临床数据，人工整理容易遗漏且版本管理混乱。", sourceStatus: "参考场景", access: 'locked' },
  { number: 23, kind: 'case', industry: '教育培训', function: '市场营销', title: "某教育机构：内容产出效率提升5倍", summary: "该K12培训机构市场部仅2人，每天手动撰写公众号文章和知乎回答，产出量低、覆盖平台少。", sourceStatus: "📎 已验证", access: 'locked' },
  { number: 24, kind: 'case', industry: '教育培训', function: '运营客服', title: "某教育机构：招生流程智能化", summary: "该机构招生流程涉及咨询→报名→材料审核→缴费→分班→开课6个环节，传统靠课程顾问人工跟进，中途流失率高。", sourceStatus: "📎 已验证", access: 'locked' },
  { number: 25, kind: 'case', industry: '教育培训', function: '产品设计', title: "某在线教育平台：课程大纲智能生成", summary: "该平台每月需新上线20+门课程，教研团队设计每门课大纲需查阅大量资料和行业标准，耗时3-5天。", sourceStatus: "参考场景", access: 'locked' },
  { number: 26, kind: 'case', industry: '教育培训', function: '数据分析', title: "某K12机构：学生学情分析自动化", summary: "该机构教务人员每月需为数千名学生手工汇总各科成绩/作业完成率/薄弱知识点，制作个性化学习报告耗时巨大。", sourceStatus: "参考场景", access: 'locked' },
  { number: 27, kind: 'case', industry: '教育培训', function: '市场营销', title: "某留学机构：案例库智能营销", summary: "该留学机构积累了大量成功案例但顾问匹配效率低——翻案例库找类似背景学生耗时且主观。", sourceStatus: "参考场景", access: 'locked' },
  { number: 28, kind: 'case', industry: '教育培训', function: '运营客服', title: "某企业培训公司：培训方案定制", summary: "该公司为企业客户提供定制化培训方案，每份方案需顾问花半天到一天手工设计课程组合和讲师匹配。", sourceStatus: "参考场景", access: 'locked' },
  { number: 29, kind: 'case', industry: '零售电商', function: '市场营销', title: "某零售团队：内容工厂模式", summary: "该品牌零售团队每天需产出大量电商详情页文案/社媒推文/广告素材，设计+文案+运营三人协作效率瓶颈明显。", sourceStatus: "📎 已验证", access: 'locked' },
  { number: 30, kind: 'case', industry: '零售电商', function: '运营客服', title: "某电商企业：私域转化率翻倍", summary: "该电商企业沉淀了大量企微好友但转化率仅3.2%——所有客户收到一样群发消息，没有分层运营。", sourceStatus: "📎 已验证", access: 'locked' },
  { number: 31, kind: 'case', industry: '零售电商', function: '运营客服', title: "某电商企业：客服团队优化", summary: "该电商企业客服团队12人，重复性问题占80%以上，大促期间人力严重不足。", sourceStatus: "📎 已验证", access: 'locked' },
  { number: 32, kind: 'case', industry: '零售电商', function: '市场营销', title: "某化妆品品牌：小红书内容矩阵", summary: "该品牌希望在小红书建立内容影响力，但团队仅1名内容运营，手工撰写效率极低。", sourceStatus: "参考场景", access: 'locked' },
  { number: 33, kind: 'case', industry: '零售电商', function: '数据分析', title: "某连锁超市：销售分析自动化", summary: "该连锁超市总部运营每周需汇总30+门店的销售数据做经营分析，手工从各店收Excel→合并→做透视表→写分析结论，每周耗去2天。", sourceStatus: "参考场景", access: 'locked' },
  { number: 34, kind: 'case', industry: '零售电商', function: '人事行政', title: "茶颜悦色：AI面试与门店运营", summary: "茶颜悦色作为高速扩张的连锁茶饮品牌，面临大规模招聘和门店运营标准化的双重挑战。", sourceStatus: "📎 官方标杆", access: 'locked' },
  { number: 35, kind: 'case', industry: '零售电商', function: '市场营销', title: "某跨境电商：多语言商品描述生成", summary: "该跨境电商卖家主营亚马逊/乐天/Shopee多平台，每次上新需为数百SKU撰写中英日韩多语言Listing，人工靠翻译软件效率极低且SEO效果差。", sourceStatus: "参考场景", access: 'locked' },
  { number: 36, kind: 'case', industry: '零售电商', function: '数据分析', title: "某品牌商：大促复盘报告自动化", summary: "该品牌每次双11/618后运营团队需花3天从各平台导出数据做复盘——数据口径不一、手动合并易错。", sourceStatus: "参考场景", access: 'locked' },
  { number: 37, kind: 'case', industry: '零售电商', function: '市场营销', title: "某品牌方：直播脚本智能生成", summary: "该消费品牌刚开始尝试直播带货，但团队缺乏专业直播策划能力，首场直播效果差。", sourceStatus: "参考场景", access: 'locked' },
  { number: 38, kind: 'case', industry: '零售电商', function: '人事行政', title: "某连锁品牌：门店员工培训自动化", summary: "该连锁零售品牌每年新开百家门店，新员工培训全依赖区域培训师出差面授，成本高且质量参差不齐。", sourceStatus: "参考场景", access: 'locked' },
  { number: 39, kind: 'case', industry: '零售电商', function: '运营客服', title: "某电商企业：客服数据分析周报", summary: "该电商企业客服主管凭经验和抽查管理客服质量，缺乏系统数据支撑。", sourceStatus: "📎 已验证", access: 'locked' },
  { number: 40, kind: 'case', industry: '物流供应链', function: '数据分析', title: "顺丰：供应链智能分析与亏损排查", summary: "顺丰面对海量物流数据，传统亏损排查需分析师跨多个系统手工拉数据、写SQL、做透视表，一笔亏损线路分析要\"熬几天\"。", sourceStatus: "📎 官方标杆", access: 'locked' },
  { number: 41, kind: 'case', industry: '物流供应链', function: '运营客服', title: "某物流公司：客户查询自动化", summary: "该物流公司客服中心每天处理上万次快递查询和时效咨询，80%以上是标准问题。", sourceStatus: "参考场景", access: 'locked' },
  { number: 42, kind: 'case', industry: '物流供应链', function: '数据分析', title: "某跨境物流公司：报关文件自动化", summary: "该跨境物流公司日均处理500+票报关，每票需准备10+种文件、手工核对HS编码和税率，出错率高且效率低。", sourceStatus: "参考场景", access: 'locked' },
  { number: 43, kind: 'case', industry: '物流供应链', function: '项目管理', title: "某供应链公司：异常订单自动处理", summary: "该供应链公司日均产生数百条异常订单（地址不详/收件人失联/拒收/破损），人工逐条判断处理方式效率极低、客户体验差。", sourceStatus: "参考场景", access: 'locked' },
  { number: 44, kind: 'case', industry: '物流供应链', function: '数据分析', title: "某冷链物流公司：温控数据监控", summary: "该冷链物流公司运输医药和生鲜产品，对温控有严格要求，传统靠人工定期检查温度记录存在监控盲区。", sourceStatus: "参考场景", access: 'locked' },
  { number: 45, kind: 'case', industry: '房地产建筑', function: '人事行政', title: "龙湖集团：多部门AI数字员工", summary: "龙湖集团在日常运营中产生大量重复性事务——行政需处理数百条会议室预订和访客登记、财务需人工核对数千张账单、营销需手动汇总各项目周报。", sourceStatus: "📎 官方标杆", access: 'locked' },
  { number: 46, kind: 'case', industry: '房地产建筑', function: '市场营销', title: "某房产中介：房源描述批量生成", summary: "该中介平台每天需发布数百套房源，经纪人手动撰写描述耗时且风格不统一。", sourceStatus: "参考场景", access: 'locked' },
  { number: 47, kind: 'case', industry: '房地产建筑', function: '项目管理', title: "某建筑公司：工程日报自动汇总", summary: "该建筑公司有8个在建项目，每个项目每日需提交施工日志——施工员手写后文员录入电脑汇总，耗时且格式混乱。", sourceStatus: "参考场景", access: 'locked' },
  { number: 48, kind: 'case', industry: '房地产建筑', function: '数据分析', title: "某物业公司：设备巡检数据管理", summary: "该物业公司管理30+个小区，消防/电梯/配电设备巡检数据分散在各项目纸质表格中，总部无法实时掌握设备状态。", sourceStatus: "参考场景", access: 'locked' },
  { number: 49, kind: 'case', industry: '房地产建筑', function: '销售客户', title: "某房产中介：客户匹配智能推荐", summary: "该中介平台房产经纪人面对数百套房源，为客户匹配全靠人脑记忆，效率低且容易遗漏优质房源。", sourceStatus: "参考场景", access: 'locked' },
  { number: 50, kind: 'case', industry: '能源环保', function: '数据分析', title: "某新能源公司：电站运维数据分析", summary: "该公司运营多个光伏/风电电站，运维数据分散在各场站SCADA系统中，总部每天需手动汇总才能了解全局。", sourceStatus: "参考场景", access: 'locked' },
  { number: 51, kind: 'case', industry: '能源环保', function: '财务合规', title: "某环保企业：碳排放报告自动生成", summary: "该企业纳入全国碳市场后需按季度提交碳排放报告和核查材料，传统人工从各生产系统手工汇总数据编制报告，耗时且易出错。", sourceStatus: "参考场景", access: 'locked' },
  { number: 52, kind: 'case', industry: '能源环保', function: '项目管理', title: "某光伏企业：电站建设进度管理", summary: "该企业同时在建多个光伏电站项目，总部难以及时掌握各项目真实进度。", sourceStatus: "参考场景", access: 'locked' },
  { number: 53, kind: 'case', industry: '能源环保', function: '人事行政', title: "某电力公司：安全培训材料自动生成", summary: "该电力公司安全培训材料需随《电力安全工作规程》更新，HR跟进吃力且材料常过期使用。", sourceStatus: "参考场景", access: 'locked' },
  { number: 54, kind: 'case', industry: '汽车交通', function: '市场营销', title: "某新能源汽车品牌：内容矩阵运营", summary: "该新能源汽车品牌需持续在多平台产出车型评测/技术解读/用车指南等内容，市场团队内容产能跟不上增长需求。", sourceStatus: "参考场景", access: 'locked' },
  { number: 55, kind: 'case', industry: '汽车交通', function: '运营客服', title: "某出行平台：司机服务知识库", summary: "该网约车平台司机端每天有海量在线咨询（接单规则/计费争议/安全事件处理），人工客服成本高。", sourceStatus: "参考场景", access: 'locked' },
  { number: 56, kind: 'case', industry: '汽车交通', function: '数据分析', title: "某4S店集团：售后运营分析", summary: "该4S店集团旗下50+门店，总部运营每月需汇总各店售后数据做经营分析，手工收集汇总周期长。", sourceStatus: "参考场景", access: 'locked' },
  { number: 57, kind: 'case', industry: '政务公共', function: '运营客服', title: "某区政务大厅：知识问答智能体", summary: "该政务大厅窗口每天面对大量重复性咨询（\"办护照要带什么\"\"房产过户要几个工作日\"），6名窗口人员满负荷运转。", sourceStatus: "📎 已验证", access: 'locked' },
  { number: 58, kind: 'case', industry: '政务公共', function: '数据分析', title: "某市数据局：民生数据分析报告", summary: "该市数据局每季度需编制民生分析报告（就业/收入/物价/社保/教育），需向十几个部门收集数据然后人工汇总分析，历时2-3周。", sourceStatus: "参考场景", access: 'locked' },
  { number: 59, kind: 'case', industry: '政务公共', function: '人事行政', title: "某机关单位：政策解读材料生成", summary: "该单位每次新政策发布后需快速产出面向公众的解读材料，但宣传科人手紧、产出慢。", sourceStatus: "参考场景", access: 'locked' },
  { number: 60, kind: 'case', industry: '媒体文娱', function: '市场营销', title: "某MCN机构：批量视频脚本生成", summary: "该MCN机构旗下20+达人每天需产出大量短视频，编导写脚本速度跟不上达人拍摄节奏。", sourceStatus: "参考场景", access: 'locked' },
  { number: 61, kind: 'case', industry: '媒体文娱', function: '数据分析', title: "某视频平台：内容运营数据周报", summary: "该视频平台运营团队每周需手工从后台拉取数十个频道的播放/互动/用户画像数据做周报，耗时半天。", sourceStatus: "参考场景", access: 'locked' },
  { number: 62, kind: 'case', industry: '媒体文娱', function: '产品设计', title: "某综艺制作公司：节目策划方案生成", summary: "该公司策划团队在提案阶段需为同一主题产出多个创意方向，人工策划数量有限且耗时长。", sourceStatus: "参考场景", access: 'locked' },
  { number: 63, kind: 'case', industry: '媒体文娱', function: '市场营销', title: "某广告公司：创意提案批量生成", summary: "该广告公司在比稿阶段需为同一客户产出3-5个差异化创意方向，策划团队加班熬夜是常态。", sourceStatus: "参考场景", access: 'locked' },
  { number: 64, kind: 'case', industry: '通信电子', function: '运营客服', title: "某通信运营商：故障自助诊断", summary: "该运营商客服中心每天接听大量宽带故障报修，80%可通过自助排查解决（重启光猫/检查线路/配置WiFi）。", sourceStatus: "参考场景", access: 'locked' },
  { number: 65, kind: 'case', industry: '通信电子', function: '项目管理', title: "某通信设备商：项目交付文档管理", summary: "该设备商每年交付数百个项目，每个项目需整理测试报告/验收文档/运维手册等大量交付件，项目助理加班整理是常态。", sourceStatus: "参考场景", access: 'locked' },
  { number: 66, kind: 'case', industry: '通信电子', function: '市场营销', title: "某芯片公司：技术白皮书自动生成", summary: "该公司芯片产品线众多，每个产品需配套技术白皮书，但工程师写文档耗时且风格不统一。", sourceStatus: "参考场景", access: 'locked' },
  { number: 67, kind: 'case', industry: '通信电子', function: '数据分析', title: "某运营商：客户投诉智能分析", summary: "该运营商每天收到海量投诉文本，人工分类分析只能覆盖少量样本。", sourceStatus: "参考场景", access: 'locked' },
  { number: 68, kind: 'case', industry: '农业食品', function: '市场营销', title: "某生鲜电商：产地溯源内容生产", summary: "该生鲜电商平台主打\"产地直发\"但详情页内容千篇一律，缺乏打动消费者的故事感。", sourceStatus: "参考场景", access: 'locked' },
  { number: 69, kind: 'case', industry: '农业食品', function: '数据分析', title: "某食品加工企业：原料价格监控", summary: "该企业原料（大豆/小麦/油脂）采购量巨大，采购时机选择直接影响成本，传统人工盯盘效率低。", sourceStatus: "参考场景", access: 'locked' },
  { number: 70, kind: 'case', industry: '农业食品', function: '运营客服', title: "某餐饮连锁：门店SOP管理", summary: "该餐饮连锁200+门店，SOP文档（菜品配方/操作流程/食品安全）更新频繁，纸质版和PDF分发后执行走样严重。", sourceStatus: "参考场景", access: 'locked' },
  { number: 71, kind: 'case', industry: '专业服务', function: '财务合规', title: "某会计师事务所：审计底稿自动化", summary: "审计忙季初级审计员大量时间花在机械性的数据抽样/计算/底稿填表上，加班严重且易出错。", sourceStatus: "参考场景", access: 'locked' },
  { number: 72, kind: 'case', industry: '专业服务', function: '财务合规', title: "司盟：邮件自动处理与审计自动化", summary: "司盟作为企业服务商面临邮件量大、审计流程长的痛点。", sourceStatus: "📎 官方标杆", access: 'locked' },
  { number: 73, kind: 'case', industry: '专业服务', function: '销售客户', title: "某律师事务所：案例检索与分析", summary: "该律所律师接到新案需快速检索相关判例和法规来评估案情，传统翻阅法律数据库耗时长。", sourceStatus: "参考场景", access: 'locked' },
  { number: 74, kind: 'case', industry: '专业服务', function: '人事行政', title: "某HR咨询公司：候选人评估自动化", summary: "该猎头公司顾问每天需筛选大量简历，视觉疲劳导致优质候选人漏过率偏高。", sourceStatus: "参考场景", access: 'locked' },
  { number: 75, kind: 'case', industry: '专业服务', function: '销售客户', title: "某管理咨询公司：客户方案书自动生成", summary: "该咨询公司每个项目需产出数十页的诊断报告和改善方案，顾问大量时间花在格式排版上。", sourceStatus: "参考场景", access: 'locked' },
  { number: 76, kind: 'case', industry: '专业服务', function: '人事行政', title: "某猎头公司：候选人报告自动生成", summary: "该猎头公司顾问为每位推荐候选人撰写推荐报告耗时30-45分钟，涵盖背景/能力/匹配度/薪资建议等模块。", sourceStatus: "参考场景", access: 'locked' },
  { number: 77, kind: 'case', industry: '游戏', function: '市场营销', title: "某游戏公司：社区运营智能化", summary: "该游戏社区运营人员每天需产出互动帖/活动公告/攻略引导等内容，还要监测舆情，工作量大。", sourceStatus: "参考场景", access: 'locked' },
  { number: 78, kind: 'case', industry: '游戏', function: '数据分析', title: "某休闲游戏公司：运营数据自动化", summary: "该公司运营每天需从多个后台导出DAU/付费率/ARPU/留存率/关卡通过率等数据做日报，耗时1-2小时。", sourceStatus: "参考场景", access: 'locked' },
  { number: 79, kind: 'case', industry: '游戏', function: '运营客服', title: "某手游公司：玩家投诉智能分类", summary: "该公司每天收到数千条玩家投诉（充值/账号/内容/BUG），客服人工逐条分类定级效率极低。", sourceStatus: "参考场景", access: 'locked' },
  { number: 80, kind: 'case', industry: '互联网软件', function: '销售客户', title: "某B2B企业：客户跟进简报自动化", summary: "该B2B企业销售同时跟进数十家客户，每次拜访前需翻CRM找历史记录准备背景，耗时且易遗漏关键信息。", sourceStatus: "📎 已验证", access: 'locked' },
  { number: 81, kind: 'case', industry: '互联网软件', function: '运营客服', title: "某教育企业：企业微信群运营", summary: "该企业在企业微信管理数十个客户群，运营人员每天花大量时间翻群找关键信息。", sourceStatus: "📎 已验证", access: 'locked' },
  { number: 82, kind: 'case', industry: '互联网软件', function: '销售客户', title: "某SaaS企业：流失客户智能挽回", summary: "该SaaS企业年客户流失率偏高，客户成功团队凭经验判断哪些客户有流失风险，往往发现时客户已流失。", sourceStatus: "📎 已验证", access: 'locked' },
  { number: 83, kind: 'case', industry: '互联网软件', function: '市场营销', title: "某电商企业：企微客户标签智能分析", summary: "该企业沉淀了数十万企微客户但标签混乱，无法实现精细化运营。", sourceStatus: "📎 已验证", access: 'locked' },
  { number: 84, kind: 'case', industry: '互联网软件', function: '市场营销', title: "某市场部：微信公众号内容矩阵", summary: "该市场部负责公司公众号矩阵（订阅号+服务号+视频号），团队2人内容产出跟不上。", sourceStatus: "参考场景", access: 'locked' },
  { number: 85, kind: 'case', industry: '互联网软件', function: '数据分析', title: "某数据岗位：Excel批量清洗效率95%", summary: "该岗位员工每天需处理多份500行左右的业务数据表，手动去重/清洗/分类统计耗时1.5小时且容易看错行。", sourceStatus: "📎 已验证", access: 'locked' },
  { number: 86, kind: 'case', industry: '互联网软件', function: '项目管理', title: "某产品经理：周报2分钟搞定", summary: "该产品经理每周五下午陷入\"写周报焦虑\"——零散的工作记录难以系统化，写出的周报总被领导批\"流水账\"。", sourceStatus: "📎 已验证", access: 'locked' },
  { number: 87, kind: 'case', industry: '互联网软件', function: '项目管理', title: "某运营团队：多文档10分钟整合", summary: "该运营团队每周需阅读整合来自不同部门的多份长文档（产品方案/会议纪要/竞品月报），人工逐份精读再整合耗时2-3小时。", sourceStatus: "📎 已验证", access: 'locked' },
  { number: 88, kind: 'case', industry: '互联网软件', function: '产品设计', title: "某互联网公司：一句话生成完整网页", summary: "该公司产品经理想快速验证一个产品创意，需制作原型页面但设计资源紧张。", sourceStatus: "📎 已验证", access: 'locked' },
  { number: 89, kind: 'case', industry: '互联网软件', function: '人事行政', title: "某科技公司：入职流程自动化", summary: "该公司年均入职200+新人，HR需逐一手动准备入职资料/制定培训计划/安排导师/推送制度文件，重复性极高。", sourceStatus: "参考场景", access: 'locked' },
  { number: 90, kind: 'case', industry: '互联网软件', function: '财务合规', title: "某科技公司：费用报销智能审核", summary: "该公司每月处理数百份报销单，财务人工逐张核对发票真伪/金额/政策合规性，耗时且疲劳易出错。", sourceStatus: "参考场景", access: 'locked' },
  { number: 91, kind: 'case', industry: '互联网软件', function: '财务合规', title: "某SaaS企业：合同审查智能化", summary: "该企业法务每月审核近百份销售和采购合同，每份需逐条比对合规清单和模板条款，审核效率成业务瓶颈。", sourceStatus: "参考场景", access: 'locked' },
  { number: 92, kind: 'case', industry: '互联网软件', function: '市场营销', title: "某创业公司：Landing Page快速迭代", summary: "该AI创业公司需频繁测试不同的产品定位和卖点表达，但设计师资源有限。", sourceStatus: "参考场景", access: 'locked' },
  { number: 93, kind: 'case', industry: '互联网软件', function: '高管战略', title: "某集团企业：AI转型路径规划", summary: "该集团企业想全面引入AI但不知从何切入，管理层担心\"花大钱买工具却用不起来\"。", sourceStatus: "参考场景", access: 'locked' },
  { number: 94, kind: 'case', industry: '互联网软件', function: '产品设计', title: "某SaaS企业：用户反馈智能分类", summary: "该企业产品团队每天面对来自应用商店/客服工单/NPS调研/社区等渠道的海量用户反馈，人工分析只能覆盖冰山一角。", sourceStatus: "参考场景", access: 'locked' },
  { number: 95, kind: 'case', industry: '互联网软件', function: '数据分析', title: "某互联网公司：月度经营分析报告", summary: "该公司每月需汇总产品/运营/市场/财务多部门数据输出经营分析报告，人工汇总核对耗时3-4天。", sourceStatus: "参考场景", access: 'locked' },
  { number: 96, kind: 'case', industry: '互联网软件', function: '运营客服', title: "某电商企业：24小时智能客服", summary: "该电商企业此前仅在白天有人工客服，夜间和周末的客户咨询大量流失。", sourceStatus: "📎 已验证", access: 'locked' },
  { number: 97, kind: 'case', industry: '互联网软件', function: '人事行政', title: "某互联网公司：简历筛选自动化", summary: "该公司HR每天面对数百封简历，初筛耗时巨大且优质候选人漏过率高。", sourceStatus: "参考场景", access: 'locked' },
  { number: 98, kind: 'case', industry: '互联网软件', function: '市场营销', title: "某教育科技公司：GEO优化获客", summary: "该公司发现传统SEO流量增长见顶，AI搜索引擎（豆包/Perplexity等）正成为新流量入口。", sourceStatus: "参考场景", access: 'locked' },
  { number: 99, kind: 'case', industry: '互联网软件', function: '项目管理', title: "某项目经理：项目风险自动识别", summary: "该项目经理同时管理3个项目，无法每天逐条审视进度和沟通记录来发现风险。", sourceStatus: "参考场景", access: 'locked' },
  { number: 100, kind: 'case', industry: '互联网软件', function: '产品设计', title: "某产品团队：竞品分析一键生成", summary: "该团队每次做竞品分析需手动搜集多个竞品的功能/定价/市场声量/融资信息，耗时2天且容易遗漏。", sourceStatus: "参考场景", access: 'locked' },
]

export function filterEnterpriseCaseCatalog(items: readonly EnterpriseCaseCatalogItem[], kind: EnterpriseCaseKind, query = '', industry = '', businessFunction = '') {
  const needle = query.trim().toLocaleLowerCase('zh-CN')
  return items.filter((item) => item.kind === kind
    && (!industry || item.industry === industry)
    && (!businessFunction || item.function === businessFunction)
    && (!needle || [item.title, item.summary, item.industry, item.function].some((value) => value.toLocaleLowerCase('zh-CN').includes(needle))))
}


